### ISSUE TITLE
[Question] Is this still working in 2022 ?

### ISSUE THREAD

**Issue by lZzozZl** [mvallim/cloud-image-ubuntu-from-scratch#1]
Hi. I would like to know is this tutorial still viable in 2022?

**Comment by mvallim** [comment]
Hi ZzozZ,

Yes, it does!

Thanks,

**Comment by mvallim** [comment]
> Hi. I would like to know is this tutorial still viable in 2022?

Hi @lZzozZl ,

Yes, it does!

Thanks,
